### PR TITLE
Optionally turn off multithreading

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by vincentsarago** [comment]
@kylebarron I'm not sure to remember what we agreed here, are we sure that `futures.ThreadPoolExecutor(max_workers=1)` is slower ?

**Comment by kylebarron** [comment]
slower than what? On Lambda it's faster than more threads.

**Comment by vincentsarago** [comment]
Is 'futures.ThreadPoolExecutor' with only 1 thread slower than using a for loop (_single_threaded)?

**Comment by kylebarron** [comment]
Oh I don't think I ever tested that, or if I did I can't remember what I found

**Comment by vincentsarago** [comment]
🤦 well in fact I did benchmark this https://github.com/vincentsarago/threadbench#1-image

So yeah not using threads seems faster!

**Comment by kylebarron** [comment]
Wow looking at those benchmarks again, not using threads vs a threadpool of 1 thread is _significantly_ faster.

Did you use this PR for testing?

**Comment by vincentsarago** [comment]
@kylebarron nope I used a simple app https://github.com/vincentsarago/threadbench/blob/master/tests/test_benchmarks.py#L26-L52

**Pull request closed without merging**
